### ISSUE TITLE
Any updates on this ?

### ISSUE THREAD

**Issue by rombru** [guidorice/points-within-polygons#1]
Hello,

I've find your work really interesting ! Unfortunatelly, the blog post about your research is not available anymore. Will it ever be again ?

Did georust hadn't enough interest compared to turf.js ?

Thank you

**Comment by guidorice** [comment]
@rombru thank you for your interest! 

I haven't been using Rust lately, and actually, have not been using WebAssembly either. 

In my day job as a full stack dev, I am mainly working with Python and Typescript. It's possible Julia language will become a useful tool for me, when it comes data science and geospatial data.

re: the referenced blog post, I will update the link in the readme. I took down the ricegeo.dev blog because I am terrible at blogging and I had not written a post in 1.5 years :) 

However, here is the referenced article, if you want to save it for future:
https://github.com/guidorice/devblog/blob/master/src/pages/points-within-polygons/index.md
